### ISSUE TITLE
Deceiver Spells Per Day

### ISSUE THREAD

**Issue by BlackHatM4stah** [CasDragon/deceiverbuff#1]
The Magic Deceiver is not getting bonus spells per day for high Charisma, leaving them stuck with a single spell per day at first level.

EDIT: Nevermind. Magic Deceivers just DON'T get bonus spells per day. Any chance you could change that?

**Comment by CasDragon** [comment]
It's possible to change it, sure. Not sure when I'll have time to get to it, but I'll add it to the list

**Comment by CasDragon** [comment]
Should be in the newest version (though untested because I still haven't gotten around to playing yet)
