### ISSUE TITLE
Only standard Deceiver spells per day, but number doesn't go down

### ISSUE THREAD

**Issue by CyberEagle1989** [CasDragon/deceiverbuff#2]
I have an extensive modlist, so it might be a conflict there, but I wanted to report it anyway.

Edit: I have deactivated all other mods and it's definitely a mod conflict. Will try to find out which mod does it.
Edit 2: It's Mystical Mayhem (not to be confused with Mythic Magic Mayhem), a mod I shouldn't have run anyway, because it is no longer updated.

**Comment by CasDragon** [comment]
Glad you found the issue!
